### ISSUE TITLE
Lack of memory

### ISSUE THREAD

**Issue by peacemo** [Western-OC2-Lab/Intrusion-Detection-System-Using-Machine-Learning#1]
How did you exactly run the Tree-base jupyter notebook on the original CIDIDS2017 dataset, it's insane!!! 16 GB of memory is far from being enough to support the whole exps.

**Comment by LiYangHart** [comment]
The original CICIDS2017 dataset is about 1GB. I'm also working on a machine with 16GB of memory and I believe it's enough to run it. Please try it on another machine.
