### ISSUE TITLE
Regarding CICIDS2017 Dataset 

### ISSUE THREAD

**Issue by NaveenSaran** [Western-OC2-Lab/Intrusion-Detection-System-Using-Machine-Learning#5]
I have the CICIDS2017 dataset file but after concatinating all Days .CSVs, the merged file is getting too long and it is not getting processed. Coould you please provide the CICIDS2017 file (as only sample file is given in data folder) to execute the code successively.

**Comment by LiYangHart** [comment]
Hi, I guess it might be due to the configuration of your computer. For copyright issues, you can request the complete dataset from the authors of this paper: https://www.researchgate.net/publication/329045441_A_detailed_analysis_of_CICIDS2017_dataset_for_designing_Intrusion_Detection_Systems
