### ISSUE TITLE
I have a question about code

### ISSUE THREAD

**Issue by White-Hongze** [Western-OC2-Lab/Intrusion-Detection-System-Using-Machine-Learning#6]
In function Anomaly_IDS, there has one code ```acc = metrics.accuracy_score(y2, result2)```, but i get a error like "Unresolved reference 'y2'", can i get your help

**Comment by LiYangHart** [comment]
The Anomaly_IDS function is only a sample code to show the logic, as we mentioned in the last cell of the code: "95% of the code has been shared, and the remaining 5% is retained for future extension.
Thank you for your interest and more details are in the paper."
