### ISSUE TITLE
Problems with oversampling

### ISSUE THREAD

**Issue by xiaozhao127** [Western-OC2-Lab/Intrusion-Detection-System-Using-Machine-Learning#7]
After setting up the oversampling parameters, when oversampling the training set of X and Y, the following error occurs please tell me how to solve it。
ValueError: Unknown label type: unknown. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

**Comment by LiYangHart** [comment]
Check your dataset labels, convert other types of labels into integers
