### ISSUE TITLE
How to access to the feature on the last section of non anomaly detection?

### ISSUE THREAD

**Issue by no00b3** [Western-OC2-Lab/Intrusion-Detection-System-Using-Machine-Learning#8]
How to access to the feature on the last section of non anomaly detection?

**Comment by LiYangHart** [comment]
what do you mean?
________________________________
From: Hafizh Anjar Saputra ***@***.***>
Sent: Sunday, July 21, 2024 2:35:57 AM
To: Western-OC2-Lab/Intrusion-Detection-System-Using-Machine-Learning ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Western-OC2-Lab/Intrusion-Detection-System-Using-Machine-Learning] How to access to the feature on the last section of non anomaly detection? (Issue #8)


How to access to the feature on the last section of non anomaly detection?

**Comment by no00b3** [comment]
Oh thanks for your reply!

I'm kinda curious how to access features did you use at stacking ensemble model (XGBoost) on multi class classification. Because it just needs 4 features, meanwhile on your selection feature you use 45 at information gain and 20 features again at Feature selection by Fast Correlation Based Filter (FCBF). I want to save it as a joblib and test it with real data that i generated by myself. Can you help me? Thanks!

**Comment by LiYangHart** [comment]
They are the 4 outputs of 4 base ML models. You can simply save these outputs.
________________________________

**Comment by no00b3** [comment]
I'm sorry, I'm new at machine learning. Before i just did it with making copies of my dataset then i put it there.
can you you help me with your approach? Thanks!

**Comment by LiYangHart** [comment]
I only answer questions about my code. I suggest you learn ML better and
understand the code clearly before you apply it to your dataset. I believe
if you understand them clearly, then there won't be any problem.

**Comment by no00b3** [comment]
Alright thanks!
