### ISSUE TITLE
FCBF Feature Selection

### ISSUE THREAD

**Issue by no00b3** [Western-OC2-Lab/Intrusion-Detection-System-Using-Machine-Learning#9]
Hi!

i have a question about your code and paper. In your code you use fcbf feature selection to your sample and you got 20 features. The question is,  did you use fcbf feature selection again in all your dataset when evaluation? Or you just use the same feature with sample? Because it takes so long when i run fcbf feature selection through all the dataset. Thanks!

**Comment by LiYangHart** [comment]
Hi, I used the same 20 features for evaluation.
________________________________
From: Hafizh Anjar Saputra ***@***.***>
Sent: Sunday, July 28, 2024 1:30:03 AM
To: Western-OC2-Lab/Intrusion-Detection-System-Using-Machine-Learning ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Western-OC2-Lab/Intrusion-Detection-System-Using-Machine-Learning] FCBF Feature Selection (Issue #9)


Hi!

i have a question with your code and paper. In your code you use fcbf feature selection to your sample and you got 20 features. The question is, did you use fcbf feature selection again in all your dataset when evaluation? Or you just use the same feature with sample? Thanks!

**Comment by no00b3** [comment]
Alright Thanks!

And how about the hyperparameter? should we find the best parameter at the whole dataset? or we can use sample best parameters? It also takes so long to find it if datasets is too large

**Comment by LiYangHart** [comment]
it’s better to find the optimal hyper-parameters of the entire dataset. This code is just an example under constraints, mainly due to the file size limit of GitHub repos.
________________________________
